services:
  python-app:
    image: nalberth/python-app:0.0.2
    volumes:
      - ./data:/data
    depends_on:
      - node-server

  node-server:
    image: nalberth/node-server:0.0.1
    ports:
      - "3000:3000"
    volumes:
      - ./data:/usr/src/app/dist/data
    environment:
      TWILIO_PHONE_NUMBER: +19388677873
      TWILIO_ACCOUNT_SID: AC6d4cb78df0edddd94dd9b3e88ed781ca
      TWILIO_AUTH_TOKEN: 1e7faf19ec5579d06fc86756eeb02357
