services:
  python-app:
    build:
      context: ./python-app
    volumes:
      - ./data:/data
    depends_on:
      - node-server

  node-server:
    build:
      context: ./node-server
    ports:
      - "3000:3000"
    volumes:
    - ./data:/usr/src/app/dist/data
    environment:
      TWILIO_PHONE_NUMBER: ${TWILIO_PHONE_NUMBER}
      TWILIO_ACCOUNT_SID: ${TWILIO_ACCOUNT_SID}
      TWILIO_AUTH_TOKEN: ${TWILIO_AUTH_TOKEN}
    env_file:
      - node-server\.env
